'use client';
import Link from 'next/link';

export default function TermsAndConditions() {
    return (
        <div className="bg-background-dark font-display text-slate-100 min-h-screen selection:bg-primary/30">
            {/* Grid Background */}
            <div className="fixed inset-0 pointer-events-none z-[-1] opacity-10" style={{ backgroundImage: 'linear-gradient(#00e5ff 1px, transparent 1px), linear-gradient(90deg, #00e5ff 1px, transparent 1px)', backgroundSize: '80px 80px' }}></div>

            <header className="p-6 border-b border-white/5 bg-black/40 backdrop-blur-md sticky top-0 z-50">
                <div className="container mx-auto flex items-center justify-between">
                    <Link href="/" className="hover:opacity-80 transition-opacity">
                        <img src="/logo.png" alt="MasterKey Labs" className="h-16 w-auto" />
                    </Link>
                    <Link href="/" className="text-xs font-bold text-primary uppercase tracking-widest hover:text-white transition-colors flex items-center gap-2">
                        <span className="material-symbols-outlined text-sm">arrow_back</span>
                        Back to Home
                    </Link>
                </div>
            </header>

            <main className="container mx-auto px-6 py-20 max-w-4xl">
                <div className="mb-12">
                    <h1 className="text-4xl md:text-5xl font-black text-white mb-4 tracking-tight">Terms & Conditions</h1>
                    <div className="h-1 w-20 bg-primary rounded-full mb-6"></div>
                    <p className="text-slate-400 text-sm">Last Updated: February 17, 2024</p>
                </div>

                <div className="space-y-10 text-slate-300 leading-relaxed">
                    <section>
                        <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-3">
                            <span className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center text-primary text-sm border border-primary/20">01</span>
                            Agreement to Terms
                        </h2>
                        <p>
                            By accessing the MasterKey Labs Diagnostic Terminal, you agree to be bound by these Terms and Conditions. Our platform is designed to provide hypothetical assessments and strategic consultancy insights.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-3">
                            <span className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center text-primary text-sm border border-primary/20">02</span>
                            Nature of Service
                        </h2>
                        <p>
                            The diagnostic reports, AI threat scores, and financial projections generated by this platform are based on the data provided by the user and curated algorithms. While we strive for maximum accuracy, these results should be viewed as strategic forecasts and not as guaranteed financial advice.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-3">
                            <span className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center text-primary text-sm border border-primary/20">03</span>
                            Intellectual Property
                        </h2>
                        <p>
                            All proprietary algorithms, UI designs, and diagnostic methodologies used in the "Terminal" are the intellectual property of MasterKey Labs. Users are granted a limited license to use the reports for internal business planning but may not resell or redistribute the platform's core code.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-3">
                            <span className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center text-primary text-sm border border-primary/20">04</span>
                            User Responsibility
                        </h2>
                        <p>
                            Users are responsible for ensuring the accuracy of the data they input. Providing falsified operational costs or business metrics will result in inaccurate diagnostic output. MasterKey Labs is not liable for business decisions made based on inaccurate user input.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-3">
                            <span className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center text-primary text-sm border border-primary/20">05</span>
                            Contact
                        </h2>
                        <p>
                            For formal inquiries regarding our service protocols or compliance, please reach out to:
                        </p>
                        <div className="mt-4 p-6 glass rounded-2xl border-white/5 inline-block">
                            <p className="text-white font-bold mb-1">MasterKey Labs Compliance</p>
                            <p className="text-primary text-sm">Email: support@masterkeylabs.in</p>
                            <p className="text-slate-500 text-xs mt-2 uppercase tracking-widest">Masterkey Operating System v2.0</p>
                        </div>
                    </section>
                </div>
            </main>

            <footer className="py-10 border-t border-white/5 text-center px-6">
                <p className="text-slate-600 text-[10px] uppercase tracking-[0.3em]">© 2024 MasterKey Labs. All Rights Reserved.</p>
            </footer>
        </div>
    );
}
